import plugins.image_loader
import plugins.image_saver
import plugins.circles
import plugins.lines
import plugins.rgb2gray
import plugins.blur
import plugins.morphology
import plugins.edge_detect
import plugins.specify_target
import plugins.template_match
import plugins.binarize
import plugins.equalize
import plugins.brightness
import plugins.color_filter
import plugins.show_graphics_items
import plugins.unsharp
import plugins.moving_average
import plugins.resize
import plugins.crop_circle
import plugins.inrange
